(function() {
    var script = document.createElement('script');
    script.type = 'application/ld+json';
    script.textContent = JSON.stringify({
        "@context": "https://schema.org",
        "@type": "MobileApplication",
        "name": "Personality Compass",
        "description": "Offline personality test app with MindPath 16, 5D, and Enneagram tests - complete privacy, no data collection",
        "applicationCategory": "LifestyleApplication",
        "operatingSystem": "iOS 14.0+, Android 8.0+",
        "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD"
        },
        "url": "https://personality-compass.app/en/",
        "sameAs": [
            "https://ferrosergio-dev.github.io/personality-compass-app"
        ],
        "featureList": [
            "100% offline operation",
            "MindPath 16 personality test",
            "MindPath 5D trait assessment",
            "Enneagram with 9 types and wings",
            "Professional PDF reports with diagrams",
            "No data collection",
            "No registration required",
            "Available in English, Russian, Estonian"
        ],
        "applicationSuite": "Personality Compass",
        "availableOnDevice": [
            "iPhone",
            "iPad",
            "Android Phone",
            "Android Tablet"
        ],
        "softwareVersion": "1.0.4",
        "releaseNotes": "Regular updates with improvements",
        "keywords": "personality test, enneagram, mindpath 16, offline psychology app, self-discovery",
        "screenshot": [
            {
                "@type": "ImageObject",
                "url": "https://personality-compass.app/images/01_en_l.webp",
                "caption": "Personality Compass main screen showing MindPath 16, Enneagram tests and My Diary",
                "width": 1080,
                "height": 2400
            },
            {
                "@type": "ImageObject",
                "url": "https://personality-compass.app/images/02_en_l.webp",
                "caption": "Test selection in Personality Compass with MindPath 16, MindPath 5D and Enneagram",
                "width": 1080,
                "height": 2400
            },
            {
                "@type": "ImageObject",
                "url": "https://personality-compass.app/images/03_en_l.webp",
                "caption": "MindPath 16 personality test questions interface in Personality Compass",
                "width": 1080,
                "height": 2400
            },
            {
                "@type": "ImageObject",
                "url": "https://personality-compass.app/images/04_en_l.webp",
                "caption": "Enneagram results showing 9 personality types in Personality Compass app",
                "width": 1080,
                "height": 2400
            },
            {
                "@type": "ImageObject",
                "url": "https://personality-compass.app/images/05_en_l.webp",
                "caption": "PDF report generated by Personality Compass with personality analysis diagrams",
                "width": 1080,
                "height": 2400
            },
            {
                "@type": "ImageObject",
                "url": "https://personality-compass.app/images/06_en_l.webp",
                "caption": "Personal Diary feature in Personality Compass for growth tracking",
                "width": 1080,
                "height": 2400
            }
        ]
    });
    document.head.appendChild(script);
})();